controller_manager:
  ros__parameters:  # Corrected to ros__parameters
    update_rate: 30
    use_sim_time: true
    # Controllers to be loaded by the controller manager
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 30.0  # Can be set higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.19
    wheel_radius: 0.0335
    use_stamped_vel: false

joint_broad:
  ros__parameters:  # Uncommented this part to ensure parameters are specified
    # Add parameters for the joint state broadcaster if needed
    use_sim_time: true  # Example parameter
